/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.ClientDisconnect', null, global);
goog.exportSymbol('proto.Dot', null, global);
goog.exportSymbol('proto.DotsUpdate', null, global);
goog.exportSymbol('proto.Message', null, global);
goog.exportSymbol('proto.Part', null, global);
goog.exportSymbol('proto.PlayerResp', null, global);
goog.exportSymbol('proto.PlayerStartReq', null, global);
goog.exportSymbol('proto.PlayerUpdateReq', null, global);
goog.exportSymbol('proto.Resize', null, global);
goog.exportSymbol('proto.SnakeInfo', null, global);
goog.exportSymbol('proto.SnakesUpdate', null, global);
goog.exportSymbol('proto.TimeInfo', null, global);
goog.exportSymbol('proto.WorldInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Message.displayName = 'proto.Message';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerstartreq: (f = msg.getPlayerstartreq()) && proto.PlayerStartReq.toObject(includeInstance, f),
    playerupdatereq: (f = msg.getPlayerupdatereq()) && proto.PlayerUpdateReq.toObject(includeInstance, f),
    playerresp: (f = msg.getPlayerresp()) && proto.PlayerResp.toObject(includeInstance, f),
    worldinfo: (f = msg.getWorldinfo()) && proto.WorldInfo.toObject(includeInstance, f),
    resize: (f = msg.getResize()) && proto.Resize.toObject(includeInstance, f),
    dotsupdate: (f = msg.getDotsupdate()) && proto.DotsUpdate.toObject(includeInstance, f),
    snakesupdate: (f = msg.getSnakesupdate()) && proto.SnakesUpdate.toObject(includeInstance, f),
    clientdisconnect: (f = msg.getClientdisconnect()) && proto.ClientDisconnect.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Message;
  return proto.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Message}
 */
proto.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.PlayerStartReq;
      reader.readMessage(value,proto.PlayerStartReq.deserializeBinaryFromReader);
      msg.setPlayerstartreq(value);
      break;
    case 2:
      var value = new proto.PlayerUpdateReq;
      reader.readMessage(value,proto.PlayerUpdateReq.deserializeBinaryFromReader);
      msg.setPlayerupdatereq(value);
      break;
    case 3:
      var value = new proto.PlayerResp;
      reader.readMessage(value,proto.PlayerResp.deserializeBinaryFromReader);
      msg.setPlayerresp(value);
      break;
    case 4:
      var value = new proto.WorldInfo;
      reader.readMessage(value,proto.WorldInfo.deserializeBinaryFromReader);
      msg.setWorldinfo(value);
      break;
    case 5:
      var value = new proto.Resize;
      reader.readMessage(value,proto.Resize.deserializeBinaryFromReader);
      msg.setResize(value);
      break;
    case 6:
      var value = new proto.DotsUpdate;
      reader.readMessage(value,proto.DotsUpdate.deserializeBinaryFromReader);
      msg.setDotsupdate(value);
      break;
    case 8:
      var value = new proto.SnakesUpdate;
      reader.readMessage(value,proto.SnakesUpdate.deserializeBinaryFromReader);
      msg.setSnakesupdate(value);
      break;
    case 9:
      var value = new proto.ClientDisconnect;
      reader.readMessage(value,proto.ClientDisconnect.deserializeBinaryFromReader);
      msg.setClientdisconnect(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerstartreq();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.PlayerStartReq.serializeBinaryToWriter
    );
  }
  f = message.getPlayerupdatereq();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.PlayerUpdateReq.serializeBinaryToWriter
    );
  }
  f = message.getPlayerresp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.PlayerResp.serializeBinaryToWriter
    );
  }
  f = message.getWorldinfo();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.WorldInfo.serializeBinaryToWriter
    );
  }
  f = message.getResize();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.Resize.serializeBinaryToWriter
    );
  }
  f = message.getDotsupdate();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.DotsUpdate.serializeBinaryToWriter
    );
  }
  f = message.getSnakesupdate();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.SnakesUpdate.serializeBinaryToWriter
    );
  }
  f = message.getClientdisconnect();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.ClientDisconnect.serializeBinaryToWriter
    );
  }
};


/**
 * optional PlayerStartReq playerStartReq = 1;
 * @return {?proto.PlayerStartReq}
 */
proto.Message.prototype.getPlayerstartreq = function() {
  return /** @type{?proto.PlayerStartReq} */ (
    jspb.Message.getWrapperField(this, proto.PlayerStartReq, 1));
};


/** @param {?proto.PlayerStartReq|undefined} value */
proto.Message.prototype.setPlayerstartreq = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.Message.prototype.clearPlayerstartreq = function() {
  this.setPlayerstartreq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasPlayerstartreq = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PlayerUpdateReq playerUpdateReq = 2;
 * @return {?proto.PlayerUpdateReq}
 */
proto.Message.prototype.getPlayerupdatereq = function() {
  return /** @type{?proto.PlayerUpdateReq} */ (
    jspb.Message.getWrapperField(this, proto.PlayerUpdateReq, 2));
};


/** @param {?proto.PlayerUpdateReq|undefined} value */
proto.Message.prototype.setPlayerupdatereq = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.Message.prototype.clearPlayerupdatereq = function() {
  this.setPlayerupdatereq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasPlayerupdatereq = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PlayerResp playerResp = 3;
 * @return {?proto.PlayerResp}
 */
proto.Message.prototype.getPlayerresp = function() {
  return /** @type{?proto.PlayerResp} */ (
    jspb.Message.getWrapperField(this, proto.PlayerResp, 3));
};


/** @param {?proto.PlayerResp|undefined} value */
proto.Message.prototype.setPlayerresp = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.Message.prototype.clearPlayerresp = function() {
  this.setPlayerresp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasPlayerresp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional WorldInfo worldInfo = 4;
 * @return {?proto.WorldInfo}
 */
proto.Message.prototype.getWorldinfo = function() {
  return /** @type{?proto.WorldInfo} */ (
    jspb.Message.getWrapperField(this, proto.WorldInfo, 4));
};


/** @param {?proto.WorldInfo|undefined} value */
proto.Message.prototype.setWorldinfo = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.Message.prototype.clearWorldinfo = function() {
  this.setWorldinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasWorldinfo = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Resize resize = 5;
 * @return {?proto.Resize}
 */
proto.Message.prototype.getResize = function() {
  return /** @type{?proto.Resize} */ (
    jspb.Message.getWrapperField(this, proto.Resize, 5));
};


/** @param {?proto.Resize|undefined} value */
proto.Message.prototype.setResize = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.Message.prototype.clearResize = function() {
  this.setResize(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasResize = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional DotsUpdate dotsUpdate = 6;
 * @return {?proto.DotsUpdate}
 */
proto.Message.prototype.getDotsupdate = function() {
  return /** @type{?proto.DotsUpdate} */ (
    jspb.Message.getWrapperField(this, proto.DotsUpdate, 6));
};


/** @param {?proto.DotsUpdate|undefined} value */
proto.Message.prototype.setDotsupdate = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.Message.prototype.clearDotsupdate = function() {
  this.setDotsupdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasDotsupdate = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional SnakesUpdate snakesUpdate = 8;
 * @return {?proto.SnakesUpdate}
 */
proto.Message.prototype.getSnakesupdate = function() {
  return /** @type{?proto.SnakesUpdate} */ (
    jspb.Message.getWrapperField(this, proto.SnakesUpdate, 8));
};


/** @param {?proto.SnakesUpdate|undefined} value */
proto.Message.prototype.setSnakesupdate = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.Message.prototype.clearSnakesupdate = function() {
  this.setSnakesupdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasSnakesupdate = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional ClientDisconnect clientDisconnect = 9;
 * @return {?proto.ClientDisconnect}
 */
proto.Message.prototype.getClientdisconnect = function() {
  return /** @type{?proto.ClientDisconnect} */ (
    jspb.Message.getWrapperField(this, proto.ClientDisconnect, 9));
};


/** @param {?proto.ClientDisconnect|undefined} value */
proto.Message.prototype.setClientdisconnect = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.Message.prototype.clearClientdisconnect = function() {
  this.setClientdisconnect(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Message.prototype.hasClientdisconnect = function() {
  return jspb.Message.getField(this, 9) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PlayerStartReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PlayerStartReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.PlayerStartReq.displayName = 'proto.PlayerStartReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PlayerStartReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PlayerStartReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PlayerStartReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlayerStartReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    skin: jspb.Message.getFieldWithDefault(msg, 1, ""),
    initiated: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PlayerStartReq}
 */
proto.PlayerStartReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PlayerStartReq;
  return proto.PlayerStartReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PlayerStartReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PlayerStartReq}
 */
proto.PlayerStartReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkin(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInitiated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PlayerStartReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PlayerStartReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PlayerStartReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlayerStartReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSkin();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInitiated();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional string skin = 1;
 * @return {string}
 */
proto.PlayerStartReq.prototype.getSkin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.PlayerStartReq.prototype.setSkin = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 initiated = 2;
 * @return {number}
 */
proto.PlayerStartReq.prototype.getInitiated = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.PlayerStartReq.prototype.setInitiated = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PlayerUpdateReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PlayerUpdateReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.PlayerUpdateReq.displayName = 'proto.PlayerUpdateReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PlayerUpdateReq.prototype.toObject = function(opt_includeInstance) {
  return proto.PlayerUpdateReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PlayerUpdateReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlayerUpdateReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    rotationasked: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
    speedmultiplier: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    initiated: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PlayerUpdateReq}
 */
proto.PlayerUpdateReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PlayerUpdateReq;
  return proto.PlayerUpdateReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PlayerUpdateReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PlayerUpdateReq}
 */
proto.PlayerUpdateReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRotationasked(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSpeedmultiplier(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInitiated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PlayerUpdateReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PlayerUpdateReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PlayerUpdateReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlayerUpdateReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRotationasked();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getSpeedmultiplier();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getInitiated();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional float rotationAsked = 1;
 * @return {number}
 */
proto.PlayerUpdateReq.prototype.getRotationasked = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.PlayerUpdateReq.prototype.setRotationasked = function(value) {
  jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float speedMultiplier = 2;
 * @return {number}
 */
proto.PlayerUpdateReq.prototype.getSpeedmultiplier = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.PlayerUpdateReq.prototype.setSpeedmultiplier = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional int64 initiated = 3;
 * @return {number}
 */
proto.PlayerUpdateReq.prototype.getInitiated = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.PlayerUpdateReq.prototype.setInitiated = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PlayerResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.PlayerResp.repeatedFields_, null);
};
goog.inherits(proto.PlayerResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.PlayerResp.displayName = 'proto.PlayerResp';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.PlayerResp.repeatedFields_ = [7,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PlayerResp.prototype.toObject = function(opt_includeInstance) {
  return proto.PlayerResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PlayerResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlayerResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    timeinfo: (f = msg.getTimeinfo()) && proto.TimeInfo.toObject(includeInstance, f),
    x: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    y: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    rotation: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    length: jspb.Message.getFieldWithDefault(msg, 6, 0),
    partsList: jspb.Message.toObjectList(msg.getPartsList(),
    proto.Part.toObject, includeInstance),
    speed: +jspb.Message.getFieldWithDefault(msg, 8, 0.0),
    eatenfoodList: jspb.Message.toObjectList(msg.getEatenfoodList(),
    proto.Dot.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PlayerResp}
 */
proto.PlayerResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PlayerResp;
  return proto.PlayerResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PlayerResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PlayerResp}
 */
proto.PlayerResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.TimeInfo;
      reader.readMessage(value,proto.TimeInfo.deserializeBinaryFromReader);
      msg.setTimeinfo(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRotation(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLength(value);
      break;
    case 7:
      var value = new proto.Part;
      reader.readMessage(value,proto.Part.deserializeBinaryFromReader);
      msg.addParts(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSpeed(value);
      break;
    case 9:
      var value = new proto.Dot;
      reader.readMessage(value,proto.Dot.deserializeBinaryFromReader);
      msg.addEatenfood(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PlayerResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PlayerResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PlayerResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PlayerResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeinfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.TimeInfo.serializeBinaryToWriter
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getRotation();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getLength();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getPartsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.Part.serializeBinaryToWriter
    );
  }
  f = message.getSpeed();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getEatenfoodList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.Dot.serializeBinaryToWriter
    );
  }
};


/**
 * optional TimeInfo timeInfo = 1;
 * @return {?proto.TimeInfo}
 */
proto.PlayerResp.prototype.getTimeinfo = function() {
  return /** @type{?proto.TimeInfo} */ (
    jspb.Message.getWrapperField(this, proto.TimeInfo, 1));
};


/** @param {?proto.TimeInfo|undefined} value */
proto.PlayerResp.prototype.setTimeinfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.PlayerResp.prototype.clearTimeinfo = function() {
  this.setTimeinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.PlayerResp.prototype.hasTimeinfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional float x = 2;
 * @return {number}
 */
proto.PlayerResp.prototype.getX = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.PlayerResp.prototype.setX = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float y = 3;
 * @return {number}
 */
proto.PlayerResp.prototype.getY = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.PlayerResp.prototype.setY = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float rotation = 4;
 * @return {number}
 */
proto.PlayerResp.prototype.getRotation = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.PlayerResp.prototype.setRotation = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional uint32 length = 6;
 * @return {number}
 */
proto.PlayerResp.prototype.getLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.PlayerResp.prototype.setLength = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated Part parts = 7;
 * @return {!Array.<!proto.Part>}
 */
proto.PlayerResp.prototype.getPartsList = function() {
  return /** @type{!Array.<!proto.Part>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Part, 7));
};


/** @param {!Array.<!proto.Part>} value */
proto.PlayerResp.prototype.setPartsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.Part=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Part}
 */
proto.PlayerResp.prototype.addParts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.Part, opt_index);
};


proto.PlayerResp.prototype.clearPartsList = function() {
  this.setPartsList([]);
};


/**
 * optional float speed = 8;
 * @return {number}
 */
proto.PlayerResp.prototype.getSpeed = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 8, 0.0));
};


/** @param {number} value */
proto.PlayerResp.prototype.setSpeed = function(value) {
  jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * repeated Dot eatenFood = 9;
 * @return {!Array.<!proto.Dot>}
 */
proto.PlayerResp.prototype.getEatenfoodList = function() {
  return /** @type{!Array.<!proto.Dot>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Dot, 9));
};


/** @param {!Array.<!proto.Dot>} value */
proto.PlayerResp.prototype.setEatenfoodList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.Dot=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Dot}
 */
proto.PlayerResp.prototype.addEatenfood = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.Dot, opt_index);
};


proto.PlayerResp.prototype.clearEatenfoodList = function() {
  this.setEatenfoodList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WorldInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.WorldInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.WorldInfo.displayName = 'proto.WorldInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WorldInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.WorldInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WorldInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WorldInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    radius: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WorldInfo}
 */
proto.WorldInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WorldInfo;
  return proto.WorldInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WorldInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WorldInfo}
 */
proto.WorldInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRadius(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WorldInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WorldInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WorldInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WorldInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRadius();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 radius = 1;
 * @return {number}
 */
proto.WorldInfo.prototype.getRadius = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.WorldInfo.prototype.setRadius = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Dot = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Dot, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Dot.displayName = 'proto.Dot';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Dot.prototype.toObject = function(opt_includeInstance) {
  return proto.Dot.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Dot} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Dot.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
    y: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    color: jspb.Message.getFieldWithDefault(msg, 3, 0),
    size: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Dot}
 */
proto.Dot.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Dot;
  return proto.Dot.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Dot} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Dot}
 */
proto.Dot.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setColor(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Dot.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Dot.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Dot} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Dot.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getColor();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional float x = 1;
 * @return {number}
 */
proto.Dot.prototype.getX = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.Dot.prototype.setX = function(value) {
  jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float y = 2;
 * @return {number}
 */
proto.Dot.prototype.getY = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.Dot.prototype.setY = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional int32 color = 3;
 * @return {number}
 */
proto.Dot.prototype.getColor = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.Dot.prototype.setColor = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 size = 4;
 * @return {number}
 */
proto.Dot.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.Dot.prototype.setSize = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DotsUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.DotsUpdate.repeatedFields_, null);
};
goog.inherits(proto.DotsUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.DotsUpdate.displayName = 'proto.DotsUpdate';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.DotsUpdate.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DotsUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.DotsUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DotsUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DotsUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    dotsList: jspb.Message.toObjectList(msg.getDotsList(),
    proto.Dot.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DotsUpdate}
 */
proto.DotsUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DotsUpdate;
  return proto.DotsUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DotsUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DotsUpdate}
 */
proto.DotsUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Dot;
      reader.readMessage(value,proto.Dot.deserializeBinaryFromReader);
      msg.addDots(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DotsUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DotsUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DotsUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DotsUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDotsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.Dot.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Dot dots = 1;
 * @return {!Array.<!proto.Dot>}
 */
proto.DotsUpdate.prototype.getDotsList = function() {
  return /** @type{!Array.<!proto.Dot>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Dot, 1));
};


/** @param {!Array.<!proto.Dot>} value */
proto.DotsUpdate.prototype.setDotsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.Dot=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Dot}
 */
proto.DotsUpdate.prototype.addDots = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.Dot, opt_index);
};


proto.DotsUpdate.prototype.clearDotsList = function() {
  this.setDotsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SnakesUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SnakesUpdate.repeatedFields_, null);
};
goog.inherits(proto.SnakesUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SnakesUpdate.displayName = 'proto.SnakesUpdate';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SnakesUpdate.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SnakesUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.SnakesUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SnakesUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SnakesUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    snakesList: jspb.Message.toObjectList(msg.getSnakesList(),
    proto.SnakeInfo.toObject, includeInstance),
    servertimestamp: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SnakesUpdate}
 */
proto.SnakesUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SnakesUpdate;
  return proto.SnakesUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SnakesUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SnakesUpdate}
 */
proto.SnakesUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.SnakeInfo;
      reader.readMessage(value,proto.SnakeInfo.deserializeBinaryFromReader);
      msg.addSnakes(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setServertimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SnakesUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SnakesUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SnakesUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SnakesUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSnakesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.SnakeInfo.serializeBinaryToWriter
    );
  }
  f = message.getServertimestamp();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * repeated SnakeInfo snakes = 1;
 * @return {!Array.<!proto.SnakeInfo>}
 */
proto.SnakesUpdate.prototype.getSnakesList = function() {
  return /** @type{!Array.<!proto.SnakeInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SnakeInfo, 1));
};


/** @param {!Array.<!proto.SnakeInfo>} value */
proto.SnakesUpdate.prototype.setSnakesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.SnakeInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SnakeInfo}
 */
proto.SnakesUpdate.prototype.addSnakes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.SnakeInfo, opt_index);
};


proto.SnakesUpdate.prototype.clearSnakesList = function() {
  this.setSnakesList([]);
};


/**
 * optional uint64 serverTimestamp = 2;
 * @return {number}
 */
proto.SnakesUpdate.prototype.getServertimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.SnakesUpdate.prototype.setServertimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Part = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Part, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Part.displayName = 'proto.Part';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Part.prototype.toObject = function(opt_includeInstance) {
  return proto.Part.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Part} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Part.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
    y: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    rotation: +jspb.Message.getFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Part}
 */
proto.Part.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Part;
  return proto.Part.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Part} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Part}
 */
proto.Part.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRotation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Part.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Part.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Part} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Part.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getRotation();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
};


/**
 * optional float x = 1;
 * @return {number}
 */
proto.Part.prototype.getX = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.Part.prototype.setX = function(value) {
  jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float y = 2;
 * @return {number}
 */
proto.Part.prototype.getY = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.Part.prototype.setY = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float rotation = 3;
 * @return {number}
 */
proto.Part.prototype.getRotation = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.Part.prototype.setRotation = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TimeInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.TimeInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.TimeInfo.displayName = 'proto.TimeInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TimeInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.TimeInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TimeInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimeInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    initiated: jspb.Message.getFieldWithDefault(msg, 1, 0),
    processing: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TimeInfo}
 */
proto.TimeInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TimeInfo;
  return proto.TimeInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TimeInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TimeInfo}
 */
proto.TimeInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInitiated(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProcessing(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TimeInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TimeInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TimeInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimeInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInitiated();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getProcessing();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional int64 initiated = 1;
 * @return {number}
 */
proto.TimeInfo.prototype.getInitiated = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.TimeInfo.prototype.setInitiated = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 processing = 2;
 * @return {number}
 */
proto.TimeInfo.prototype.getProcessing = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.TimeInfo.prototype.setProcessing = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SnakeInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SnakeInfo.repeatedFields_, null);
};
goog.inherits(proto.SnakeInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SnakeInfo.displayName = 'proto.SnakeInfo';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SnakeInfo.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SnakeInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.SnakeInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SnakeInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SnakeInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    x: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    y: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    rotation: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    rotationasked: +jspb.Message.getFieldWithDefault(msg, 5, 0.0),
    length: jspb.Message.getFieldWithDefault(msg, 6, 0),
    pathList: jspb.Message.toObjectList(msg.getPathList(),
    proto.Part.toObject, includeInstance),
    speed: +jspb.Message.getFieldWithDefault(msg, 8, 0.0),
    skin: jspb.Message.getFieldWithDefault(msg, 9, ""),
    lastprocessedonserver: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SnakeInfo}
 */
proto.SnakeInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SnakeInfo;
  return proto.SnakeInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SnakeInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SnakeInfo}
 */
proto.SnakeInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRotation(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRotationasked(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLength(value);
      break;
    case 7:
      var value = new proto.Part;
      reader.readMessage(value,proto.Part.deserializeBinaryFromReader);
      msg.addPath(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSpeed(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkin(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastprocessedonserver(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SnakeInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SnakeInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SnakeInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SnakeInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getRotation();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getRotationasked();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getLength();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getPathList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.Part.serializeBinaryToWriter
    );
  }
  f = message.getSpeed();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getSkin();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getLastprocessedonserver();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.SnakeInfo.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.SnakeInfo.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float x = 2;
 * @return {number}
 */
proto.SnakeInfo.prototype.getX = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.SnakeInfo.prototype.setX = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float y = 3;
 * @return {number}
 */
proto.SnakeInfo.prototype.getY = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.SnakeInfo.prototype.setY = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float rotation = 4;
 * @return {number}
 */
proto.SnakeInfo.prototype.getRotation = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.SnakeInfo.prototype.setRotation = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float rotationAsked = 5;
 * @return {number}
 */
proto.SnakeInfo.prototype.getRotationasked = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.SnakeInfo.prototype.setRotationasked = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional uint32 length = 6;
 * @return {number}
 */
proto.SnakeInfo.prototype.getLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.SnakeInfo.prototype.setLength = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated Part path = 7;
 * @return {!Array.<!proto.Part>}
 */
proto.SnakeInfo.prototype.getPathList = function() {
  return /** @type{!Array.<!proto.Part>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Part, 7));
};


/** @param {!Array.<!proto.Part>} value */
proto.SnakeInfo.prototype.setPathList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.Part=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Part}
 */
proto.SnakeInfo.prototype.addPath = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.Part, opt_index);
};


proto.SnakeInfo.prototype.clearPathList = function() {
  this.setPathList([]);
};


/**
 * optional float speed = 8;
 * @return {number}
 */
proto.SnakeInfo.prototype.getSpeed = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 8, 0.0));
};


/** @param {number} value */
proto.SnakeInfo.prototype.setSpeed = function(value) {
  jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional string skin = 9;
 * @return {string}
 */
proto.SnakeInfo.prototype.getSkin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.SnakeInfo.prototype.setSkin = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional uint64 lastProcessedOnServer = 10;
 * @return {number}
 */
proto.SnakeInfo.prototype.getLastprocessedonserver = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.SnakeInfo.prototype.setLastprocessedonserver = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Resize = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Resize, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Resize.displayName = 'proto.Resize';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Resize.prototype.toObject = function(opt_includeInstance) {
  return proto.Resize.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Resize} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Resize.toObject = function(includeInstance, msg) {
  var f, obj = {
    width: jspb.Message.getFieldWithDefault(msg, 1, 0),
    height: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Resize}
 */
proto.Resize.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Resize;
  return proto.Resize.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Resize} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Resize}
 */
proto.Resize.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Resize.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Resize.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Resize} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Resize.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 width = 1;
 * @return {number}
 */
proto.Resize.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.Resize.prototype.setWidth = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 height = 2;
 * @return {number}
 */
proto.Resize.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.Resize.prototype.setHeight = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ClientDisconnect = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ClientDisconnect, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ClientDisconnect.displayName = 'proto.ClientDisconnect';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ClientDisconnect.prototype.toObject = function(opt_includeInstance) {
  return proto.ClientDisconnect.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ClientDisconnect} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ClientDisconnect.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ClientDisconnect}
 */
proto.ClientDisconnect.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ClientDisconnect;
  return proto.ClientDisconnect.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ClientDisconnect} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ClientDisconnect}
 */
proto.ClientDisconnect.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ClientDisconnect.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ClientDisconnect.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ClientDisconnect} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ClientDisconnect.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.ClientDisconnect.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ClientDisconnect.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto);
